#!/bin/bash

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"


xrandr --output eDP-1 --off --output HDMI-1 --primary --mode 1920x1200
feh --bg-scale $HOME/.config/berry/wallpaper
parcellite &
flameshot &
